### PR TITLE
WIP Acceptance tests for api documentation

### PR DESCRIPTION
**Pull request by tochman**
I added a scenario for viewing tests but I can't get them to pass. I'm getting 

```
No route matches [GET] "/swagger/dist/index.html"
```

skarmavbild 2016-02-22 kl 10 46 42

There was also an extra line in your `.gitignore` that made all files in `/tmp` to be included in version control. I removed that.
I would merge this in and try to make the tests pass. One downside I see with using Swagger is that we need to run

```
bundle exec rake swagger:docs
```

... so the documentation is not generated automatically. But we can overcome that.

Another thing is that you should create a separate feature branch before starting to work on a feature. The way this it is now you have more commits then you should have in this...

### CODE REVIEW

**Comment by freeranger** [comment]
I tried yesterday adding a test but it didn't work but I don't know enough ruby or rails to figure out why it didn't work.

routes.rb contains

```
get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')
```

So should you be going to /api instead?

On the swagger docs site: https://github.com/richhollis/swagger-docs
they recommend you add a precompile step:

```
#Rakefile or lib/task/precompile_overrides.rake
namespace :assets do
  task :precompile do
    Rake::Task['assets:precompile'].invoke
    Rake::Task['swagger:docs'].invoke
  end
end
```

to generate the docs at deploy time, or of course we could add to the default rake task or no doubt many other things...

If I'm reading the PR correctly, it seems to have a bunch of other stuff in it - like removal of the Httparty from my other PR.  Is this because this branch is based off develop as was before you accepted that PR whereas your PR is based off develop as it currently is, with that PR merged?
Should you have taken my swagger PR as base rather than develop as base and made the changes to that?  

Also you said "Another thing is that you should create a separate feature branch before starting to work on a feature. The way this it is now you have more commits then you should have in this..."

I don't know what you mean - when I started work on this I did:
- git checkout -b swagger
- did all my stuff
- checked in and committed locally
- did a "git push -u origin swagger" to push to new remote branch (following instruction here: http://stackoverflow.com/questions/2765421/push-a-new-local-branch-to-a-remote-git-repository-and-track-it-too)
- created my PR from that

What should I have done differently there?

Sorry, new to this whole PR thing - we use SVN in work :/

**Comment by tochman** [comment]
Okay so I did THIS PR to your develop because it seemed that you had all the `swagger` files and commits in there. My mistake.

I will close this one and make a new one to the correct branch. 

You need to figure out your git workflow so you get the right code in every feature branch. Basically its all about not touching your own `develop` for accept for creating new branches and pulling from upstream. 

So let's say you work on something on a feature branch `branch_one` and you committed some code. Now, for some reason you want to start working on another feature. Here's what you need to do:
- Go back to your `develop` branch

```
git checkout develop
```
- Make sure you have the latest code from `upstream`

```
git pull upstream develop
```
-  Create a new branch

```
git checkout -b branch_two
```

By doing this you avoid including the commits from `branch_one` in your new feature branch `branch_two`

I have no clue how to set up routes for Swagger, sorry.

**Comment by freeranger** [comment]
That's what I did do though with my PR, which is why it contains only the swagger stuff - I don't know what extra commits you mean?  My swagger branch has 8 commits and they are all related to this branch only....

**Comment by tochman** [comment]
I was thrown off by this commit on your `develop` branch: https://github.com/tochman/project_unify/commit/7c4d707a49b1c53885e186295c369689d163d4be

Any way, I created a new PR.

**Pull request closed without merging**
